# Generated by Django 4.1 on 2022-08-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biblioteka',
            new_name='Ksiazki',
        ),
    ]
