# Generated by Django 4.1 on 2022-08-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_alter_kategoria_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazki',
            name='kategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategoria', to='biblioteka.kategoria'),
        ),
    ]
