# Generated by Django 4.1 on 2022-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_ksiazki_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='kategoria',
            field=models.CharField(blank=True, choices=[('fsci', 'fantasy,science-fiction'), ('h', 'horror'), ('k', 'kryminał'), ('lm', 'literatura młodzieżowa'), ('lo', 'literatura obyczajowa'), ('ph', 'powieść historyczna'), ('pp', 'powieść przygodowa'), ('pn', 'literatura popularno-naukowa'), ('b', 'bajki'), ('bl', 'baśnie,legendy'), ('ld', 'literatura dziecięca'), ('o', 'opowiadania'), ('w', 'wiersze'), ('d', 'dramat')], default='pp', help_text='Kategoria', max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
    ]
