# Generated by Django 4.1 on 2022-08-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.CharField(max_length=200)),
                ('czy_opcje', models.BooleanField(blank=True, null=True)),
                ('opcja1', models.CharField(blank=True, max_length=100, null=True)),
                ('opcja2', models.CharField(blank=True, max_length=100, null=True)),
                ('opcja3', models.CharField(blank=True, max_length=100, null=True)),
                ('opcja4', models.CharField(blank=True, max_length=100, null=True)),
                ('odpowiedz', models.CharField(blank=True, max_length=250, null=True)),
                ('numer_pytania', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=250, unique=True)),
                ('opis', models.CharField(blank=True, max_length=350, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('tresc', models.TextField()),
                ('data_utowrzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('data_publikacji', models.DateTimeField(blank=True, null=True)),
                ('czyOpublikowane', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.uzytkownicy')),
            ],
            options={
                'ordering': ['data_publikacji'],
            },
        ),
    ]
