# Generated by Django 4.1 on 2022-08-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pytanie',
            new_name='Ankieta',
        ),
    ]
