# Generated by Django 3.2.13 on 2022-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_wpis_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
