# Generated by Django 3.2.13 on 2022-08-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_wpis_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankieta',
            name='odpowiedz',
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpowiedz', models.CharField(max_length=250)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ankieta')),
            ],
        ),
    ]
