# Generated by Django 4.1 on 2022-08-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_odpowiedz_pyt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpowiedz',
            name='pyt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ankieta'),
        ),
    ]
