# Generated by Django 4.1 on 2022-08-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_zdjecia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumenty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('plik', models.FileField(upload_to='dokumenty')),
            ],
        ),
    ]
