# Generated by Django 4.1 on 2022-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_dokumenty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankieta',
            name='czy_opcje',
        ),
        migrations.AlterField(
            model_name='ankieta',
            name='numer_pytania',
            field=models.IntegerField(default=1),
        ),
    ]
